### ISSUE TITLE
服务器重启就会出现这个问题

### ISSUE THREAD

**Issue by BigAppleClass** [myunco/LiteTeleport#3]
[15:44:57 INFO]: [LiteTeleport] Enabling LiteTeleport v1.9.1
[15:44:57 INFO]: nullnullsethomeConsume: 2L.0
[15:44:57 ERROR]: Error occurred while enabling LiteTeleport v1.9.1 (Is it up to date?)
java.lang.NumberFormatException: For input string: "2L.0"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at ml.mcos.liteteleport.consume.ConsumeInfo.getConsumeAmountDouble(ConsumeInfo.java:127) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at ml.mcos.liteteleport.config.Config.getConsumeDouble(Config.java:126) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at ml.mcos.liteteleport.config.Config.getSethomeConsume(Config.java:134) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at ml.mcos.liteteleport.config.Config.loadConfig(Config.java:59) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at ml.mcos.liteteleport.LiteTeleport.initConfig(LiteTeleport.java:63) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at ml.mcos.liteteleport.LiteTeleport.onEnable(LiteTeleport.java:52) ~[[传送]LiteTeleport-1.9.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-272]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-272]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:44:57 INFO]: [LiteTeleport] Disabling LiteTeleport v1.9.1

**Comment by myunco** [comment]
sethomeConsume: 2L 不要写2L 要写2.0L

**Comment by BigAppleClass** [comment]
好的

**Comment by myunco** [comment]
已在1.9.2快照版本中修复此问题
